FEED: "https://www.reddit.com/r/MotorsportsReplays.rss"
DOWNLOAD_TYPES:
  - "motogp"
DOWNLOAD_DIR: "./downloads"
QUALITY: "1080"
INTERVAL_MINS: 60
DELETE_OLD_FILES: true
DELETE_OLD_FILES_THRESHOLD: 10
ENABLE_NOTIFICATIONS: true
NOTIFICATION_TYPES:
  - "telegram"
  - "gotify"
GOTIFY_URL: 192.168.1.200:7152
GOTIFY_TOKEN: "1234567890"
GOTIFY_APP_ID: "motogp-dl"
TELEGRAM_TOKEN: "1234567890:ABCDEF"
TELEGRAM_CHAT_ID: "1234567890"
