FEED: "https://www.reddit.com/r/MotorsportsReplays.rss"
DOWNLOAD_DIR: "./downloads"
INTERVAL_MINS: 60
MAX_DOWNLOADS_PER_DAY: 1
DELETE_OLD_FILES: true
DELETE_OLD_FILES_THRESHOLD: 10
ENABLE_NOTIFICATIONS: true
NOTIFICATION_TYPES:
  - "telegram"
  # - "gotify"
GOTIFY_URL: 192.168.1.200:7152
GOTIFY_TOKEN:
GOTIFY_APP_ID: "motogp-dl"
TELEGRAM_TOKEN:
TELEGRAM_CHAT_ID:
POSITIVE_FILTERS:
  - (?i)motogp
  - 1080p|1080
  - (?i)MotoGP.\d{4}x[1-3]?[0-9].\w+
  - (?i)race
  - (?i)spr
  - (?i)sprint
  - (?i)rac
NEGATIVE_FILTERS:
  - (?i)^(?!.*motogp).*
  - (?i)qual
  - (?i)q[1-4]
  - (?i)fp[1-4]
  - (?i)qualifying
  - (?i)request
  - (?i)practice